set(LIB_NAME lib_intf)
set(LIB_VERSION 1.0.0)
set(LIB_XC_SRCS src/intf.xc src/intf2.xc)
set(LIB_INCLUDES api)
set(LIB_DEPENDENT_MODULES "")
set(LIB_COMPILER_FLAGS -DLIB_INTF_OPTION=1)
set(LIB_COMPILER_FLAGS_intf.xc -DINTF_FILE_OPTION=1)

XMOS_REGISTER_MODULE()
