set(LIB_NAME lib_static0)
set(LIB_VERSION 1.0.0)
set(LIB_ARCH xs3a)
set(LIB_INCLUDES api)
set(LIB_DEPENDENT_MODULES "")

set(LIB_ADD_SRC_DIRS src)
set(LIB_ADD_INC_DIRS inc)

set(LIB_COMPILER_FLAGS -DLIB_STATIC0_OPTION=1)

XMOS_REGISTER_STATIC_LIB()
