set(LIB_NAME lib_static0)
set(LIB_VERSION 1.0.0)
set(LIB_INCLUDES api)
set(LIB_ARCHIVE_INCLUDES api)
set(LIB_DEPENDENT_MODULES "")
set(LIB_COMPILER_FLAGS -DLIB_STATIC0_OPTION=1)
set(LIB_ARCHIVE_FLAGS -DLIB_STATIC0_ARCHIVE_OPTION=1)

XMOS_REGISTER_STATIC_LIB()
